/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import control.Models;
import entities.Customer;
import entities.Product;
import entities.Sale;
import entities.SaleItem;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import persistencia.CustomerRepositoryImpl;
import persistencia.ProductRepositoryImpl;
import persistencia.SaleItemRepositoryImpl;
import persistencia.SaleRepositoryImpl;

/**
 *
 * @author Invitado
 */
public class FrmMenu extends javax.swing.JFrame {

    private EntityManager em;
    private Sale currentSale;
    private SaleItemRepositoryImpl saleItemRep;
    private CustomerRepositoryImpl customerRep;
    private ProductRepositoryImpl productRep;
    private SaleRepositoryImpl saleRep;

    private List<SaleItem> lstSaleItems;
    private List<Product> lstProducts;
    private List<Customer> lstCustomers;
    
    private float total;
    private float totalDiscount;
    private float discount;

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();

        EntityManagerFactory managerFactory
                = Persistence.createEntityManagerFactory("SistemaVentasPU");
        em
                = managerFactory.createEntityManager();

        em.getTransaction().begin();

        lstSaleItems = new ArrayList<>();

        saleItemRep = new SaleItemRepositoryImpl(em, SaleItem.class);
        customerRep = new CustomerRepositoryImpl(em, Customer.class);
        productRep = new ProductRepositoryImpl(em, Product.class);
        saleRep = new SaleRepositoryImpl(em, Sale.class);

        currentSale = new Sale();
        
        refreshCustomers();

        updateProductList();
    }

    private void updateMainTable() {

        updateProductList();
        
        
        
        
        this.jtblSale.setModel(Models.saleItemTableModel(lstSaleItems));
        
        
        this.total=0;
        for (SaleItem lstSaleItem : lstSaleItems) {
            this.total+=lstSaleItem.getTotal();
        }
        
        if(txtDiscount.getText().length()>0){
            this.totalDiscount=(this.total*Float.parseFloat(txtDiscount.getText()))/100;
            this.discount=Float.parseFloat(txtDiscount.getText());
            this.total-=this.totalDiscount;
            this.lblTotalDiscount.setText("DISCOUNT: $"+String.valueOf(this.totalDiscount));
            
        }
        this.lblTotal.setText("TOTAL: $"+String.valueOf(this.total));
    }

    private void updateProductList() {
        lstProducts = productRep.findAll();
        DefaultListModel mdl = new DefaultListModel();

        for (int i = 0; i < lstProducts.size(); i++) {
            if(lstProducts.get(i).getStock()>0)
                mdl.add(i, lstProducts.get(i));
        }

        lstAvailableProducts.setModel(mdl);
    }
    
    private void refreshCustomers(){
        lstCustomers = customerRep.findAll();

        this.cbxCustomers.setModel(Models.customersComboBoxModel(lstCustomers));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        btnCharge = new javax.swing.JButton();
        lblTotalDiscount = new javax.swing.JLabel();
        lblProducts = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAvailableProducts = new javax.swing.JList<>();
        lblThisSale = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblSale = new javax.swing.JTable();
        cbxCustomers = new javax.swing.JComboBox<>();
        lblCustomer = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        lblPercent = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        lblDiscount = new javax.swing.JLabel();
        btnRefreshCustomers = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCustomers = new javax.swing.JMenu();
        menuProducts = new javax.swing.JMenu();
        menuProviders = new javax.swing.JMenu();
        menuCategories = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotal.setText("TOTAL: $0.00");

        btnCharge.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCharge.setText("Charge");
        btnCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChargeActionPerformed(evt);
            }
        });

        lblTotalDiscount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotalDiscount.setText("DISCOUNT: $0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCharge, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addComponent(lblTotalDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblProducts.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblProducts.setText("Products list:");

        lstAvailableProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAvailableProductsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstAvailableProducts);

        lblThisSale.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblThisSale.setText("On this sale:");

        jtblSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Price", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblSaleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtblSale);

        lblCustomer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCustomer.setText("Customer");

        btnRefresh.setText("Refresh products");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblPercent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPercent.setText("%");

        lblDiscount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiscount.setText("Discount:");

        btnRefreshCustomers.setText("Refresh customers");
        btnRefreshCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshCustomersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxCustomers, 0, 266, Short.MAX_VALUE)
                            .addComponent(btnRefreshCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(lblThisSale, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 758, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPercent)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiscount)
                    .addComponent(btnRefreshCustomers))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCustomers)
                            .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addComponent(lblProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)))
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(lblThisSale, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(477, Short.MAX_VALUE)))
        );

        menuCustomers.setText("Customers");
        menuCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCustomersMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCustomers);

        menuProducts.setText("Products");
        menuProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProductsMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuProducts);

        menuProviders.setText("Providers");
        menuProviders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProvidersMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuProviders);

        menuCategories.setText("Categories");
        menuCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCategoriesMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCategories);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCustomersMouseClicked
        FrmCustomer frm = new FrmCustomer(em);
        frm.setVisible(true);
    }//GEN-LAST:event_menuCustomersMouseClicked

    private void menuProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductsMouseClicked
        FrmProduct frm = new FrmProduct(em);
        frm.setVisible(true);
    }//GEN-LAST:event_menuProductsMouseClicked

    private void menuProvidersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProvidersMouseClicked
        FrmProvider frm = new FrmProvider(em);
        frm.setVisible(true);
    }//GEN-LAST:event_menuProvidersMouseClicked

    private void menuCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCategoriesMouseClicked
        FrmCategory frm = new FrmCategory(em);
        frm.setVisible(true);
    }//GEN-LAST:event_menuCategoriesMouseClicked

    private void jtblSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblSaleMouseClicked

    }//GEN-LAST:event_jtblSaleMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        updateProductList();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void lstAvailableProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAvailableProductsMouseClicked
        if (evt.getClickCount() == 2) {
            int index = lstAvailableProducts.locationToIndex(evt.getPoint());
            if (index >= 0) {
                
                Object o = lstAvailableProducts.getModel().getElementAt(index);
                index=-1;
                for (SaleItem lstSaleItem : lstSaleItems) {
                    if (lstSaleItem.getProduct() == o) {
                        index = lstSaleItems.indexOf(lstSaleItem);
                        System.out.println(lstSaleItem.getProduct());
                        break;
                    }
                }
                if (index>=0) {

                    if (lstSaleItems.get(index).addOne()) {
                        updateMainTable();
                    } else {
                        updateProductList();
                        
                    }
                } else {
                    SaleItem saleItem = new SaleItem();
                    saleItem.setSale(currentSale);
                    saleItem.setProduct((Product)o);
                    lstSaleItems.add(saleItem);
                    updateMainTable();
                }
            }
        }
    }//GEN-LAST:event_lstAvailableProductsMouseClicked

    private void btnChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChargeActionPerformed
        if(lstSaleItems.size()>0&&this.total>0){
            
            currentSale.setCustomer((Customer)cbxCustomers.getSelectedItem());
            currentSale.setDate(new Date());
            currentSale.setDiscount(this.totalDiscount);
            currentSale.setTotal(this.total);
            
            saleRep.save(currentSale);
            saleRep.commit();
            
            for (SaleItem lstSaleItem : lstSaleItems) {
                productRep.save(lstSaleItem.getProduct());
                productRep.commit();
                saleItemRep.save(lstSaleItem);
                saleItemRep.commit();
            }
           
            JOptionPane.showMessageDialog(this, "A new sale has been saved");
            
            this.lstSaleItems.clear();
            updateMainTable();
            this.total=0;
            currentSale=new Sale();
            this.txtDiscount.setText("");
            this.lblTotal.setText("TOTAL: $0.0");
            this.lblTotalDiscount.setText("DISCOUNT: $0.0");
        }
    }//GEN-LAST:event_btnChargeActionPerformed

    private void btnRefreshCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshCustomersActionPerformed
        refreshCustomers();
    }//GEN-LAST:event_btnRefreshCustomersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCharge;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefreshCustomers;
    private javax.swing.JComboBox<String> cbxCustomers;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtblSale;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblPercent;
    private javax.swing.JLabel lblProducts;
    private javax.swing.JLabel lblThisSale;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalDiscount;
    private javax.swing.JList<String> lstAvailableProducts;
    private javax.swing.JMenu menuCategories;
    private javax.swing.JMenu menuCustomers;
    private javax.swing.JMenu menuProducts;
    private javax.swing.JMenu menuProviders;
    private javax.swing.JTextField txtDiscount;
    // End of variables declaration//GEN-END:variables
}
